// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import QuantityToggleController from "controllers/quantity_toggle_controller"
application.register("quantity-toggle", QuantityToggleController)

import ScrollNavigationController from "controllers/scroll_navigation_controller"
application.register("scroll-navigation", ScrollNavigationController)

import AlgoliaSearchController from "controllers/algolia_search_controller"
application.register("algolia-search", AlgoliaSearchController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import CollapseController from "controllers/collapse_controller"
application.register("collapse", CollapseController)

import InputCounterController from "controllers/input_counter_controller"
application.register("input-counter", InputCounterController)

import StripeCheckoutController from "controllers/stripe_checkout_controller"
application.register("stripe-checkout", StripeCheckoutController)