development:
  abandoned_cart_soft_deletion:
    class: SoftDeleteAbandonedCartsJob
    schedule: every day
  abandoned_cart_hard_deletion:
    class: HardDeleteAbandonedCartsJob
    schedule: every day