# Generated by Rails - I just changed User >> Admin
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[new create]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: 'Try again later.' }

  def new
  end

  def create
    if admin = Admin.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for admin
      redirect_to admins_orders_url
    else
      redirect_to new_sessions_path, alert: 'Try another email address or password.'
    end
  end

  def destroy
    terminate_session
    redirect_to admin_login_sessions_path
  end
end
